#include "graph/graph.h"
#include "graph/node.h"

#include "ops/operator.h"

#include "runtime/executor.h"
#include "runtime/cuda_memory_pool.h"
#include "runtime/device_transfer.h"

#include "tensor/tensor.h"

#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

// Generated by ChatGPT-6, already reviewed by Zhehang


// ==================================================
// CUDA error checking
// ==================================================

void check_cuda(
    cudaError_t status,
    const char* operation
)
{
    if(status != cudaSuccess)
    {
        throw std::runtime_error(
            std::string(operation) + ": " +
            cudaGetErrorString(status)
        );
    }
}


// ==================================================
// Compare CPU and CUDA outputs.
// Supports causal-mask negative infinity.
// ==================================================

bool compare_tensors(
    const Tensor& actual,
    const Tensor& expected,
    float tolerance = 1e-5f
)
{
    if(actual.shape() != expected.shape())
    {
        return false;
    }

    float max_diff = 0.0f;

    for(std::size_t i = 0; i < actual.size(); i++)
    {
        const float a = actual[i];
        const float b = expected[i];

        // Masked positions must both be negative infinity.
        if(
            std::isinf(a) &&
            std::isinf(b) &&
            a < 0.0f &&
            b < 0.0f
        )
        {
            continue;
        }

        if(!std::isfinite(a) || !std::isfinite(b))
        {
            std::cout
                << "Non-finite mismatch at index " << i
                << ": actual=" << a
                << ", expected=" << b
                << std::endl;

            return false;
        }

        const float diff = std::fabs(a - b);

        max_diff = std::max(max_diff, diff);

        if(diff > tolerance)
        {
            std::cout
                << "Mismatch at index " << i
                << ": actual=" << a
                << ", expected=" << b
                << ", diff=" << diff
                << std::endl;

            return false;
        }
    }

    std::cout << "Max difference: " << max_diff << "\n";

    return true;
}


// ==================================================
// Utility: create a CPU tensor from values.
// ==================================================

Tensor make_cpu_tensor(
    const std::string& name,
    const std::vector<int>& shape,
    const std::vector<float>& values
)
{
    Tensor tensor(name, shape);

    if(tensor.size() != values.size())
    {
        throw std::runtime_error(
            "Input data size does not match tensor shape."
        );
    }

    for(std::size_t i = 0; i < values.size(); i++)
    {
        tensor[i] = values[i];
    }

    return tensor;
}


// ==================================================
// GPU test fixture.
// Owns input CUDA allocations.
// The Executor owns its output allocations.
// ==================================================

class GpuTestContext
{
public:
    GpuTestContext() = default;

    GpuTestContext(const GpuTestContext&) = delete;   // Meaning forbid using existed instance to create another instance. Have double free risk
    GpuTestContext& operator=(const GpuTestContext&) = delete;   // 同样禁止通过等号进行复制构造

    ~GpuTestContext()
    {
        // Ensure launched kernels have finished before
        // the external input pool is destroyed.
        cudaDeviceSynchronize();   // 等待当前设备之前提交的CUDA工作全部完成
    }

    void add_input(const Tensor& host)
    {
        float* device_ptr =
            input_pool_.allocate(host.size());

        Tensor device(
            host.name(),
            host.shape(),
            device_ptr,
            DeviceType::CUDA
        );

        copy_host_to_device(host, device);

        executor.add_tensor(device);
    }

    Executor executor;

private:
    CudaMemoryPool input_pool_;
};


// ==================================================
// Test 1: CUDA Executor MatMul
// ==================================================

bool test_executor_matmul()
{
    constexpr int M = 3;
    constexpr int K = 4;
    constexpr int N = 2;

    Tensor A = make_cpu_tensor(
        "A",
        {M, K},
        {
            1, 2, 3, 4,
            5, 6, 7, 8,
            9, 10, 11, 12
        }
    );

    Tensor B = make_cpu_tensor(
        "B",
        {K, N},
        {
            1, 2,
            3, 4,
            5, 6,
            7, 8
        }
    );

    Tensor expected("expected", {M, N});

    matmul(
        A.data(),
        B.data(),
        expected.data(),
        M, K, N
    );

    GpuTestContext context;

    context.add_input(A);
    context.add_input(B);

    context.executor.register_tensor(
        "C",
        {M, N},
        DeviceType::CUDA
    );

    Graph graph;

    graph.add_node(
        Node(
            "matmul_node",
            "MatMul",
            {"A", "B"},
            {"C"}
        )
    );

    graph.build_dependencies();

    context.executor.run(graph);

    check_cuda(
        cudaGetLastError(),
        "MatMul kernel launch"
    );

    check_cuda(
        cudaDeviceSynchronize(),   // 保证GPU所有的线程也完成了
        "MatMul synchronization"
    );

    Tensor actual("actual", {M, N});

    copy_device_to_host(
        context.executor.get_tensor("C"),
        actual
    );

    return compare_tensors(actual, expected);
}


// ==================================================
// Test 2: CUDA Executor Attention Scores
// ==================================================

bool test_executor_attention_scores()
{
    constexpr int seq_len = 3;
    constexpr int head_dim = 2;

    Tensor Q = make_cpu_tensor(
        "Q",
        {seq_len, head_dim},
        {
            4, 6,
            12, 14,
            20, 22
        }
    );

    Tensor K = make_cpu_tensor(
        "K",
        {seq_len, head_dim},
        {
            4, 7,
            12, 19,
            20, 31
        }
    );

    Tensor expected(
        "expected",
        {seq_len, seq_len}
    );

    attention_scores(
        Q.data(),
        K.data(),
        expected.data(),
        seq_len,
        head_dim
    );

    GpuTestContext context;

    context.add_input(Q);
    context.add_input(K);

    context.executor.register_tensor(
        "scores",
        {seq_len, seq_len},
        DeviceType::CUDA
    );

    Graph graph;

    graph.add_node(
        Node(
            "scores_node",
            "AttentionScores",
            {"Q", "K"},
            {"scores"}
        )
    );

    graph.build_dependencies();

    context.executor.run(graph);

    check_cuda(
        cudaGetLastError(),
        "AttentionScores kernel launch"
    );

    check_cuda(
        cudaDeviceSynchronize(),
        "AttentionScores synchronization"
    );

    Tensor actual(
        "actual",
        {seq_len, seq_len}
    );

    copy_device_to_host(
        context.executor.get_tensor("scores"),
        actual
    );

    return compare_tensors(actual, expected);
}


// ==================================================
// Test 3: CUDA Executor Attention Softmax
// ==================================================

bool test_executor_attention_softmax()
{
    constexpr int seq_len = 4;

    const float neg_inf =
        -std::numeric_limits<float>::infinity();

    Tensor scores = make_cpu_tensor(
        "scores",
        {seq_len, seq_len},
        {
            2, neg_inf, neg_inf, neg_inf,
            1, 3,       neg_inf, neg_inf,
            0.5f, 1, 2, neg_inf,
            1, 2, 3, 4
        }
    );

    Tensor expected(
        "expected",
        {seq_len, seq_len}
    );

    attention_softmax(
        scores.data(),
        expected.data(),
        seq_len
    );

    GpuTestContext context;

    context.add_input(scores);

    context.executor.register_tensor(
        "weights",
        {seq_len, seq_len},
        DeviceType::CUDA
    );

    Graph graph;

    graph.add_node(
        Node(
            "softmax_node",
            "AttentionSoftmax",
            {"scores"},
            {"weights"}
        )
    );

    graph.build_dependencies();

    context.executor.run(graph);

    check_cuda(
        cudaGetLastError(),
        "AttentionSoftmax kernel launch"
    );

    check_cuda(
        cudaDeviceSynchronize(),
        "AttentionSoftmax synchronization"
    );

    Tensor actual(
        "actual",
        {seq_len, seq_len}
    );

    copy_device_to_host(
        context.executor.get_tensor("weights"),
        actual
    );

    if(!compare_tensors(actual, expected))
    {
        return false;
    }

    // Each row must sum to one.
    // Future-token probabilities must be zero.
    for(int row = 0; row < seq_len; row++)
    {
        float row_sum = 0.0f;

        for(int col = 0; col < seq_len; col++)
        {
            const float value =
                actual[row * seq_len + col];

            row_sum += value;

            if(col > row && value != 0.0f)
            {
                return false;
            }
        }

        if(std::fabs(row_sum - 1.0f) > 1e-5f)
        {
            return false;
        }
    }

    return true;
}


// ==================================================
// Main
// ==================================================

int main()
{
    try
    {
        const bool matmul_ok =
            test_executor_matmul();

        const bool scores_ok =
            test_executor_attention_scores();

        const bool softmax_ok =
            test_executor_attention_softmax();

        std::cout
            << "CUDA Executor MatMul: "
            << (matmul_ok ? "PASS" : "FAIL")
            << "\n";

        std::cout
            << "CUDA Executor AttentionScores: "
            << (scores_ok ? "PASS" : "FAIL")
            << "\n";

        std::cout
            << "CUDA Executor AttentionSoftmax: "
            << (softmax_ok ? "PASS" : "FAIL")
            << "\n";

        return (
            matmul_ok &&
            scores_ok &&
            softmax_ok
        ) ? 0 : 1;
    }
    catch(const std::exception& e)
    {
        std::cerr
            << "Test exception: "
            << e.what()
            << std::endl;

        return 1;
    }
}