#include "graph/graph.h"
#include "graph/node.h"

#include "ops/operator.h"

#include "runtime/executor.h"
#include "runtime/cuda_memory_pool.h"
#include "runtime/device_transfer.h"

#include "tensor/tensor.h"

#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

// Generated by ChatGPT-6, already reviewed by Zhehang


// ==================================================
// CUDA error checking
// ==================================================

void check_cuda(
    cudaError_t status,
    const char* operation
)
{
    if(status != cudaSuccess)
    {
        throw std::runtime_error(
            std::string(operation) + ": " +
            cudaGetErrorString(status)
        );
    }
}


// ==================================================
// Compare CPU and CUDA outputs.
// Supports causal-mask negative infinity.
// ==================================================

bool compare_tensors(
    const Tensor& actual,
    const Tensor& expected,
    float tolerance = 1e-5f
)
{
    if(actual.shape() != expected.shape())
    {
        return false;
    }

    float max_diff = 0.0f;

    for(std::size_t i = 0; i < actual.size(); i++)
    {
        const float a = actual[i];
        const float b = expected[i];

        // Masked positions must both be negative infinity.
        if(
            std::isinf(a) &&
            std::isinf(b) &&
            a < 0.0f &&
            b < 0.0f
        )
        {
            continue;
        }

        if(!std::isfinite(a) || !std::isfinite(b))
        {
            std::cout
                << "Non-finite mismatch at index " << i
                << ": actual=" << a
                << ", expected=" << b
                << std::endl;

            return false;
        }

        const float diff = std::fabs(a - b);

        max_diff = std::max(max_diff, diff);

        if(diff > tolerance)
        {
            std::cout
                << "Mismatch at index " << i
                << ": actual=" << a
                << ", expected=" << b
                << ", diff=" << diff
                << std::endl;

            return false;
        }
    }

    std::cout << "Max difference: " << max_diff << "\n";

    return true;
}


// ==================================================
// Utility: create a CPU tensor from values.
// ==================================================

Tensor make_cpu_tensor(
    const std::string& name,
    const std::vector<int>& shape,
    const std::vector<float>& values
)
{
    Tensor tensor(name, shape);

    if(tensor.size() != values.size())
    {
        throw std::runtime_error(
            "Input data size does not match tensor shape."
        );
    }

    for(std::size_t i = 0; i < values.size(); i++)
    {
        tensor[i] = values[i];
    }

    return tensor;
}


// ==================================================
// GPU test fixture.
// Owns input CUDA allocations.
// The Executor owns its output allocations.
// ==================================================

class GpuTestContext
{
public:
    GpuTestContext() = default;

    GpuTestContext(const GpuTestContext&) = delete;   // Meaning forbid using existed instance to create another instance. Have double free risk
    GpuTestContext& operator=(const GpuTestContext&) = delete;   // 同样禁止通过等号进行复制构造

    ~GpuTestContext()
    {
        // Ensure launched kernels have finished before
        // the external input pool is destroyed.
        cudaDeviceSynchronize();   // 等待当前设备之前提交的CUDA工作全部完成
    }

    void add_input(const Tensor& host)
    {
        float* device_ptr =
            input_pool_.allocate(host.size());

        Tensor device(
            host.name(),
            host.shape(),
            device_ptr,
            DeviceType::CUDA
        );

        copy_host_to_device(host, device);

        executor.add_tensor(device);
    }

    Executor executor;

private:
    CudaMemoryPool input_pool_;
};


// ==================================================
// Test 1: CUDA Executor MatMul
// ==================================================

bool test_executor_matmul()
{
    constexpr int M = 3;
    constexpr int K = 4;
    constexpr int N = 2;

    Tensor A = make_cpu_tensor(
        "A",
        {M, K},
        {
            1, 2, 3, 4,
            5, 6, 7, 8,
            9, 10, 11, 12
        }
    );

    Tensor B = make_cpu_tensor(
        "B",
        {K, N},
        {
            1, 2,
            3, 4,
            5, 6,
            7, 8
        }
    );

    Tensor expected("expected", {M, N});

    matmul(
        A.data(),
        B.data(),
        expected.data(),
        M, K, N
    );

    GpuTestContext context;

    context.add_input(A);
    context.add_input(B);

    context.executor.register_tensor(
        "C",
        {M, N},
        DeviceType::CUDA
    );

    Graph graph;

    graph.add_node(
        Node(
            "matmul_node",
            "MatMul",
            {"A", "B"},
            {"C"}
        )
    );

    graph.build_dependencies();

    context.executor.run(graph);

    check_cuda(
        cudaGetLastError(),
        "MatMul kernel launch"
    );

    check_cuda(
        cudaDeviceSynchronize(),   // 保证GPU所有的线程也完成了
        "MatMul synchronization"
    );

    Tensor actual("actual", {M, N});

    copy_device_to_host(
        context.executor.get_tensor("C"),
        actual
    );

    return compare_tensors(actual, expected);
}


// ==================================================
// Test 2: CUDA Executor Attention Scores
// ==================================================

bool test_executor_attention_scores()
{
    constexpr int seq_len = 3;
    constexpr int head_dim = 2;

    Tensor Q = make_cpu_tensor(
        "Q",
        {seq_len, head_dim},
        {
            4, 6,
            12, 14,
            20, 22
        }
    );

    Tensor K = make_cpu_tensor(
        "K",
        {seq_len, head_dim},
        {
            4, 7,
            12, 19,
            20, 31
        }
    );

    Tensor expected(
        "expected",
        {seq_len, seq_len}
    );

    attention_scores(
        Q.data(),
        K.data(),
        expected.data(),
        seq_len,
        head_dim
    );

    GpuTestContext context;

    context.add_input(Q);
    context.add_input(K);

    context.executor.register_tensor(
        "scores",
        {seq_len, seq_len},
        DeviceType::CUDA
    );

    Graph graph;

    graph.add_node(
        Node(
            "scores_node",
            "AttentionScores",
            {"Q", "K"},
            {"scores"}
        )
    );

    graph.build_dependencies();

    context.executor.run(graph);

    check_cuda(
        cudaGetLastError(),
        "AttentionScores kernel launch"
    );

    check_cuda(
        cudaDeviceSynchronize(),
        "AttentionScores synchronization"
    );

    Tensor actual(
        "actual",
        {seq_len, seq_len}
    );

    copy_device_to_host(
        context.executor.get_tensor("scores"),
        actual
    );

    return compare_tensors(actual, expected);
}


// ==================================================
// Test 3: CUDA Executor Attention Softmax
// ==================================================

bool test_executor_attention_softmax()
{
    constexpr int seq_len = 4;

    const float neg_inf =
        -std::numeric_limits<float>::infinity();

    Tensor scores = make_cpu_tensor(
        "scores",
        {seq_len, seq_len},
        {
            2, neg_inf, neg_inf, neg_inf,
            1, 3,       neg_inf, neg_inf,
            0.5f, 1, 2, neg_inf,
            1, 2, 3, 4
        }
    );

    Tensor expected(
        "expected",
        {seq_len, seq_len}
    );

    attention_softmax(
        scores.data(),
        expected.data(),
        seq_len
    );

    GpuTestContext context;

    context.add_input(scores);

    context.executor.register_tensor(
        "weights",
        {seq_len, seq_len},
        DeviceType::CUDA
    );

    Graph graph;

    graph.add_node(
        Node(
            "softmax_node",
            "AttentionSoftmax",
            {"scores"},
            {"weights"}
        )
    );

    graph.build_dependencies();

    context.executor.run(graph);

    check_cuda(
        cudaGetLastError(),
        "AttentionSoftmax kernel launch"
    );

    check_cuda(
        cudaDeviceSynchronize(),
        "AttentionSoftmax synchronization"
    );

    Tensor actual(
        "actual",
        {seq_len, seq_len}
    );

    copy_device_to_host(
        context.executor.get_tensor("weights"),
        actual
    );

    if(!compare_tensors(actual, expected))
    {
        return false;
    }

    // Each row must sum to one.
    // Future-token probabilities must be zero.
    for(int row = 0; row < seq_len; row++)
    {
        float row_sum = 0.0f;

        for(int col = 0; col < seq_len; col++)
        {
            const float value =
                actual[row * seq_len + col];

            row_sum += value;

            if(col > row && value != 0.0f)
            {
                return false;
            }
        }

        if(std::fabs(row_sum - 1.0f) > 1e-5f)
        {
            return false;
        }
    }

    return true;
}




// ==================================================
// Test 4:
// End-to-End CUDA Scaled Dot-Product Attention
//
// Q, K, V
//    |
//    v
// AttentionScores
//    |
//    v
// AttentionSoftmax
//    |
//    v
// MatMul(weights, V)
//    |
//    v
// output
// ==================================================

bool test_executor_attention_end_to_end()
{
    constexpr int seq_len = 4;
    constexpr int head_dim = 3;

    constexpr float tolerance = 1e-5f;

    // ==================================================
    // Step 1: Create CPU input tensors.
    // ==================================================

    Tensor Q = make_cpu_tensor(
        "Q",
        {seq_len, head_dim},
        {
            1.0f, 0.5f, 0.2f,
            0.3f, 1.0f, 0.4f,
            0.6f, 0.2f, 1.0f,
            1.0f, 0.8f, 0.5f
        }
    );

    Tensor K = make_cpu_tensor(
        "K",
        {seq_len, head_dim},
        {
            0.8f, 0.2f, 0.5f,
            0.1f, 1.0f, 0.3f,
            0.5f, 0.4f, 0.9f,
            0.9f, 0.6f, 0.2f
        }
    );

    Tensor V = make_cpu_tensor(
        "V",
        {seq_len, head_dim},
        {
            1.0f, 2.0f, 3.0f,
            4.0f, 5.0f, 6.0f,
            7.0f, 8.0f, 9.0f,
            10.0f, 11.0f, 12.0f
        }
    );


    // ==================================================
    // Step 2: Calculate CPU reference.
    // ==================================================

    Tensor expected(
        "expected",
        {seq_len, head_dim}
    );

    scaled_dot_product_attention(
        Q.data(),
        K.data(),
        V.data(),
        expected.data(),
        seq_len,
        head_dim
    );


    // ==================================================
    // Step 3: Create CUDA test context.
    // ==================================================

    GpuTestContext context;

    context.add_input(Q);
    context.add_input(K);
    context.add_input(V);


    // ==================================================
    // Step 4: Register CUDA output tensors.
    //
    // Intermediate:
    // scores, weights
    //
    // Final:
    // output
    // ==================================================

    context.executor.register_tensor(
        "scores",
        {seq_len, seq_len},
        DeviceType::CUDA
    );

    context.executor.register_tensor(
        "weights",
        {seq_len, seq_len},
        DeviceType::CUDA
    );

    context.executor.register_tensor(
        "output",
        {seq_len, head_dim},
        DeviceType::CUDA
    );


    // ==================================================
    // Step 5: Build computation graph.
    // ==================================================

    Graph graph;


    // scores = QK^T / sqrt(head_dim) + causal mask
    graph.add_node(
        Node(
            "attention_scores_node",
            "AttentionScores",
            {"Q", "K"},
            {"scores"}
        )
    );


    // weights = softmax(scores)
    graph.add_node(
        Node(
            "attention_softmax_node",
            "AttentionSoftmax",
            {"scores"},
            {"weights"}
        )
    );


    // output = weights * V
    graph.add_node(
        Node(
            "attention_output_node",
            "MatMul",
            {"weights", "V"},
            {"output"}
        )
    );


    // Build producer-consumer dependencies.
    graph.build_dependencies();


    // ==================================================
    // Step 6: Validate execution order.
    // ==================================================

    const std::vector<int> order =
        graph.topological_sort();

    std::cout
        << "Graph execution order:"
        << std::endl;

    for(int node_index : order)
    {
        std::cout
            << "  "
            << graph.nodes()[node_index].name()
            << std::endl;
    }


    // ==================================================
    // Step 7: Execute full attention graph on GPU.
    // ==================================================

    context.executor.run(graph);


    // Check kernel launch errors.
    check_cuda(
        cudaGetLastError(),
        "End-to-End Attention kernel launch"
    );


    // Wait for all CUDA kernels to finish.
    check_cuda(
        cudaDeviceSynchronize(),
        "End-to-End Attention synchronization"
    );


    // ==================================================
    // Step 8: Obtain final CUDA output.
    // ==================================================

    Tensor& device_output =
        context.executor.get_tensor("output");


    if(device_output.device() != DeviceType::CUDA)
    {
        throw std::runtime_error(
            "Attention output is not on CUDA."
        );
    }


    // ==================================================
    // Step 9: D2H transfer.
    // ==================================================

    Tensor actual(
        "actual",
        {seq_len, head_dim}
    );

    copy_device_to_host(
        device_output,
        actual
    );


    // ==================================================
    // Step 10: Compare CPU and CUDA outputs.
    // ==================================================

    const bool correct =
        compare_tensors(
            actual,
            expected,
            tolerance
        );


    // ==================================================
    // Step 11: Print outputs.
    // ==================================================

    std::cout
        << "\nCPU Attention Output:"
        << std::endl;

    for(int row = 0; row < seq_len; row++)
    {
        for(int col = 0; col < head_dim; col++)
        {
            std::cout
                << expected[row * head_dim + col]
                << " ";
        }

        std::cout << std::endl;
    }


    std::cout
        << "\nCUDA Attention Output:"
        << std::endl;

    for(int row = 0; row < seq_len; row++)
    {
        for(int col = 0; col < head_dim; col++)
        {
            std::cout
                << actual[row * head_dim + col]
                << " ";
        }

        std::cout << std::endl;
    }


    // ==================================================
    // Step 12: Final result.
    // ==================================================

    std::cout
        << "\nEnd-to-End CUDA Attention: "
        << (correct ? "PASS" : "FAIL")
        << std::endl;


    return correct;
}








// ==================================================
// Main
// ==================================================

int main()
{
    try
    {
        const bool matmul_ok =
            test_executor_matmul();

        const bool scores_ok =
            test_executor_attention_scores();

        const bool softmax_ok =
            test_executor_attention_softmax();

        const bool attention_ok = test_executor_attention_end_to_end();

        std::cout
            << "CUDA Executor MatMul: "
            << (matmul_ok ? "PASS" : "FAIL")
            << "\n";

        std::cout
            << "CUDA Executor AttentionScores: "
            << (scores_ok ? "PASS" : "FAIL")
            << "\n";

        std::cout
            << "CUDA Executor AttentionSoftmax: "
            << (softmax_ok ? "PASS" : "FAIL")
            << "\n";

        std::cout
            << "CUDA Executor End-to-End Attention: "
            << (attention_ok ? "PASS" : "FAIL")
            << "\n";

        return (
            matmul_ok &&
            scores_ok &&
            softmax_ok &&
            attention_ok
        ) ? 0 : 1;
    }
    catch(const std::exception& e)
    {
        std::cerr
            << "Test exception: "
            << e.what()
            << std::endl;

        return 1;
    }
}