# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/chenzhehang/Desktop/Nvidia Intern/High-Performance-Deep-Learning-Inference-Framework-for-Attention-Mechanisms"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/chenzhehang/Desktop/Nvidia Intern/High-Performance-Deep-Learning-Inference-Framework-for-Attention-Mechanisms"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/chenzhehang/Desktop/Nvidia Intern/High-Performance-Deep-Learning-Inference-Framework-for-Attention-Mechanisms/CMakeFiles" "/Users/chenzhehang/Desktop/Nvidia Intern/High-Performance-Deep-Learning-Inference-Framework-for-Attention-Mechanisms//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/chenzhehang/Desktop/Nvidia Intern/High-Performance-Deep-Learning-Inference-Framework-for-Attention-Mechanisms/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gemm_test

# Build rule for target.
gemm_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_test
.PHONY : gemm_test

# fast build rule for target.
gemm_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/build
.PHONY : gemm_test/fast

#=============================================================================
# Target rules for targets named gemm_benchmark

# Build rule for target.
gemm_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_benchmark
.PHONY : gemm_benchmark

# fast build rule for target.
gemm_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/build
.PHONY : gemm_benchmark/fast

benchmark/benchmark_gemm.o: benchmark/benchmark_gemm.cpp.o
.PHONY : benchmark/benchmark_gemm.o

# target to build an object file
benchmark/benchmark_gemm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/benchmark/benchmark_gemm.cpp.o
.PHONY : benchmark/benchmark_gemm.cpp.o

benchmark/benchmark_gemm.i: benchmark/benchmark_gemm.cpp.i
.PHONY : benchmark/benchmark_gemm.i

# target to preprocess a source file
benchmark/benchmark_gemm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/benchmark/benchmark_gemm.cpp.i
.PHONY : benchmark/benchmark_gemm.cpp.i

benchmark/benchmark_gemm.s: benchmark/benchmark_gemm.cpp.s
.PHONY : benchmark/benchmark_gemm.s

# target to generate assembly for a file
benchmark/benchmark_gemm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/benchmark/benchmark_gemm.cpp.s
.PHONY : benchmark/benchmark_gemm.cpp.s

src/gemm/naive_gemm.o: src/gemm/naive_gemm.cpp.o
.PHONY : src/gemm/naive_gemm.o

# target to build an object file
src/gemm/naive_gemm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/naive_gemm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/naive_gemm.cpp.o
.PHONY : src/gemm/naive_gemm.cpp.o

src/gemm/naive_gemm.i: src/gemm/naive_gemm.cpp.i
.PHONY : src/gemm/naive_gemm.i

# target to preprocess a source file
src/gemm/naive_gemm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/naive_gemm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/naive_gemm.cpp.i
.PHONY : src/gemm/naive_gemm.cpp.i

src/gemm/naive_gemm.s: src/gemm/naive_gemm.cpp.s
.PHONY : src/gemm/naive_gemm.s

# target to generate assembly for a file
src/gemm/naive_gemm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/naive_gemm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/naive_gemm.cpp.s
.PHONY : src/gemm/naive_gemm.cpp.s

src/gemm/reordered_gemm.o: src/gemm/reordered_gemm.cpp.o
.PHONY : src/gemm/reordered_gemm.o

# target to build an object file
src/gemm/reordered_gemm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/reordered_gemm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/reordered_gemm.cpp.o
.PHONY : src/gemm/reordered_gemm.cpp.o

src/gemm/reordered_gemm.i: src/gemm/reordered_gemm.cpp.i
.PHONY : src/gemm/reordered_gemm.i

# target to preprocess a source file
src/gemm/reordered_gemm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/reordered_gemm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/reordered_gemm.cpp.i
.PHONY : src/gemm/reordered_gemm.cpp.i

src/gemm/reordered_gemm.s: src/gemm/reordered_gemm.cpp.s
.PHONY : src/gemm/reordered_gemm.s

# target to generate assembly for a file
src/gemm/reordered_gemm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/reordered_gemm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/reordered_gemm.cpp.s
.PHONY : src/gemm/reordered_gemm.cpp.s

src/gemm/unrolled_gemm.o: src/gemm/unrolled_gemm.cpp.o
.PHONY : src/gemm/unrolled_gemm.o

# target to build an object file
src/gemm/unrolled_gemm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/unrolled_gemm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/unrolled_gemm.cpp.o
.PHONY : src/gemm/unrolled_gemm.cpp.o

src/gemm/unrolled_gemm.i: src/gemm/unrolled_gemm.cpp.i
.PHONY : src/gemm/unrolled_gemm.i

# target to preprocess a source file
src/gemm/unrolled_gemm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/unrolled_gemm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/unrolled_gemm.cpp.i
.PHONY : src/gemm/unrolled_gemm.cpp.i

src/gemm/unrolled_gemm.s: src/gemm/unrolled_gemm.cpp.s
.PHONY : src/gemm/unrolled_gemm.s

# target to generate assembly for a file
src/gemm/unrolled_gemm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/gemm/unrolled_gemm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/gemm/unrolled_gemm.cpp.s
.PHONY : src/gemm/unrolled_gemm.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/matrix.o: src/utils/matrix.cpp.o
.PHONY : src/utils/matrix.o

# target to build an object file
src/utils/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/utils/matrix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/utils/matrix.cpp.o
.PHONY : src/utils/matrix.cpp.o

src/utils/matrix.i: src/utils/matrix.cpp.i
.PHONY : src/utils/matrix.i

# target to preprocess a source file
src/utils/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/utils/matrix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/utils/matrix.cpp.i
.PHONY : src/utils/matrix.cpp.i

src/utils/matrix.s: src/utils/matrix.cpp.s
.PHONY : src/utils/matrix.s

# target to generate assembly for a file
src/utils/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_test.dir/build.make CMakeFiles/gemm_test.dir/src/utils/matrix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/utils/matrix.cpp.s
.PHONY : src/utils/matrix.cpp.s

src/utils/timer.o: src/utils/timer.cpp.o
.PHONY : src/utils/timer.o

# target to build an object file
src/utils/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/utils/timer.cpp.o
.PHONY : src/utils/timer.cpp.o

src/utils/timer.i: src/utils/timer.cpp.i
.PHONY : src/utils/timer.i

# target to preprocess a source file
src/utils/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/utils/timer.cpp.i
.PHONY : src/utils/timer.cpp.i

src/utils/timer.s: src/utils/timer.cpp.s
.PHONY : src/utils/timer.s

# target to generate assembly for a file
src/utils/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_benchmark.dir/build.make CMakeFiles/gemm_benchmark.dir/src/utils/timer.cpp.s
.PHONY : src/utils/timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gemm_benchmark"
	@echo "... gemm_test"
	@echo "... benchmark/benchmark_gemm.o"
	@echo "... benchmark/benchmark_gemm.i"
	@echo "... benchmark/benchmark_gemm.s"
	@echo "... src/gemm/naive_gemm.o"
	@echo "... src/gemm/naive_gemm.i"
	@echo "... src/gemm/naive_gemm.s"
	@echo "... src/gemm/reordered_gemm.o"
	@echo "... src/gemm/reordered_gemm.i"
	@echo "... src/gemm/reordered_gemm.s"
	@echo "... src/gemm/unrolled_gemm.o"
	@echo "... src/gemm/unrolled_gemm.i"
	@echo "... src/gemm/unrolled_gemm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/matrix.o"
	@echo "... src/utils/matrix.i"
	@echo "... src/utils/matrix.s"
	@echo "... src/utils/timer.o"
	@echo "... src/utils/timer.i"
	@echo "... src/utils/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

