#include "graph/graph.h"

void Graph::add_node(const Node& node){
    nodes_.push_back(node);
}


void Graph::build_dependencies(){

    edges_.clear();
    edges_.resize(nodes_.size());
    indegrees_.assign(nodes_.size(), 0);  // Set all node's indegree to 0.


    // tensor_producer["A", 1] means node 1 produces the tensor named "A"
    std::unordered_map<std::string, int> tensor_producer;


    // Figure which node produce which tensor
    for(int i = 0; i < static_cast<int>(nodes_.size()); i++){
        for(const std::string& output : nodes_[i].outputs())
            tensor_producer[output] = i;
    }


    // Build edges from producer node to consumer node
    // Like node A produce a tensor and node b treats that tensor as input then build A -> B.
    for(int consumer = 0; consumer < static_cast<int>(nodes_.size()); consumer++){
        for(const std::string& input : nodes_[consumer].inputs()){

            auto it = tensor_producer.find(input);   // it at here will be std::unordered_map<std::string, int>::iterator

            if(it == tensor_producer.end()) continue;  // Means this input not generated by any node on the graph

            int producer = it -> second;
            edges_[producer].push_back(consumer);

            indegrees_[consumer]++;

        }
    }

}




// Getter
const std::vector<Node>& Graph::nodes() const{ 
    return nodes_;
}


const std::vector<std::vector<int>>& Graph::edges() const{
    return edges_;
}


const std::vector<int>& Graph::indegrees() const{
    return indegrees_;
}



