#include "graph/graph.h"



void Graph::add_node(const Node& node){
    nodes_.push_back(node);
}



// Graph build implementation
void Graph::build_dependencies(){

    edges_.clear();
    edges_.resize(nodes_.size());
    indegrees_.assign(nodes_.size(), 0);  // Set all node's indegree to 0.


    // tensor_producer["A", 1] means node 1 produces the tensor named "A"
    std::unordered_map<std::string, int> tensor_producer;


    // Figure which node produce which tensor
    for(int i = 0; i < static_cast<int>(nodes_.size()); i++){
        for(const std::string& output : nodes_[i].outputs())
            tensor_producer[output] = i;
    }


    // Build edges from producer node to consumer node
    // Like node A produce a tensor and node b treats that tensor as input then build A -> B.
    for(int consumer = 0; consumer < static_cast<int>(nodes_.size()); consumer++){
        for(const std::string& input : nodes_[consumer].inputs()){

            auto it = tensor_producer.find(input);   // it at here will be std::unordered_map<std::string, int>::iterator

            if(it == tensor_producer.end()) continue;  // Means this input not generated by any node on the graph

            int producer = it -> second;
            edges_[producer].push_back(consumer);

            indegrees_[consumer]++;

        }
    }

}




// Getter
const std::vector<Node>& Graph::nodes() const{ 
    return nodes_;
}


const std::vector<std::vector<int>>& Graph::edges() const{
    return edges_;
}


const std::vector<int>& Graph::indegrees() const{
    return indegrees_;
}




// Tpoloigical sort implementation
std::vector<int> Graph::topological_sort() const {
    
    // Have been promised that this function will not change any inner value, therefore, we need to copy a indegree 
    std::vector<int> indegree = indegrees_;
    std::queue<int> ready;
    std::vector<int> order;

    // 1. Find all nodes which can be executed
    for(int i = 0; i < static_cast<int>(nodes_.size()); i++){
        if(indegree[i] == 0) ready.push(i);
    }


    // 2. Process ready nodes
    while(!ready.empty()){
        int current = ready.front();
        ready.pop();
        order.push_back(current);

        // 3. remove every outgoing edge of current node.
        for(int next : edges_[current]){
            indegree[next] --;

            if(indegree[next] == 0) ready.push(next);
        }
    }


    // 4. Detect Cycle   
    // 原理很简单，如果一个图没有环，那必定每个node都可以被加入输出集合中
    if(order.size() != nodes_.size()){
        throw std::runtime_error("graph contains a cycle.");
    }


    return order;


}

