// This test completely generated by ChatGPT, I have already reviewed all code.



#include <iostream>
#include <stdexcept>

#include "graph/parser.h"
#include "runtime/executor.h"
#include "tensor/tensor.h"


int main()
{
    Graph graph =
        GraphParser::parse(
            "models/tests/test_full_attention_graph.json"
        );


    // --------------------------------------------------
    // Persistent / external tensors
    // --------------------------------------------------

    Tensor X(
        "X",
        {3, 4}
    );

    Tensor W_q(
        "W_q",
        {4, 2}
    );

    Tensor W_k(
        "W_k",
        {4, 2}
    );

    Tensor W_v(
        "W_v",
        {4, 2}
    );


    float X_data[] = {
        1, 0, 1, 0,
        0, 1, 0, 1,
        1, 1, 1, 1
    };


    float W_q_data[] = {
        1, 0,
        0, 1,
        1, 0,
        0, 1
    };


    float W_k_data[] = {
        1, 0,
        0, 1,
        0, 1,
        1, 0
    };


    float W_v_data[] = {
        1, 0,
        0, 1,
        1, 1,
        1, -1
    };


    for(std::size_t i = 0; i < X.size(); i++)
    {
        X[i] =
            X_data[i];
    }


    for(std::size_t i = 0; i < W_q.size(); i++)
    {
        W_q[i] =
            W_q_data[i];

        W_k[i] =
            W_k_data[i];

        W_v[i] =
            W_v_data[i];
    }


    // --------------------------------------------------
    // Executor
    // --------------------------------------------------

    Executor executor;


    // Persistent tensors already own memory
    executor.add_tensor(X);
    executor.add_tensor(W_q);
    executor.add_tensor(W_k);
    executor.add_tensor(W_v);


    // --------------------------------------------------
    // Register tensor metadata only
    // No memory allocated yet
    // --------------------------------------------------

    executor.register_tensor(
        "Q",
        {3, 2}
    );

    executor.register_tensor(
        "K",
        {3, 2}
    );

    executor.register_tensor(
        "V",
        {3, 2}
    );

    executor.register_tensor(
        "scores",
        {3, 3}
    );

    executor.register_tensor(
        "weights",
        {3, 3}
    );

    executor.register_tensor(
        "output",
        {3, 2}
    );


    // --------------------------------------------------
    // Run
    // --------------------------------------------------

    executor.run(
        graph
    );


    // --------------------------------------------------
    // Test 1:
    // Final output still exists and is correct
    // --------------------------------------------------

    const Tensor& output =
        executor.get_tensor(
            "output"
        );


    std::cout
        << "Attention Output:"
        << std::endl;


    for(int i = 0; i < 3; i++)
    {
        for(int j = 0; j < 2; j++)
        {
            std::cout
                << output[i * 2 + j]
                << " ";
        }

        std::cout
            << std::endl;
    }


    // --------------------------------------------------
    // Test 2:
    // Intermediate tensors should be released
    // --------------------------------------------------

    const std::string intermediate_tensors[] = {
        "Q",
        "K",
        "V",
        "scores",
        "weights"
    };


    std::cout
        << std::endl
        << "Released intermediate tensors:"
        << std::endl;


    for(
        const std::string& name :
        intermediate_tensors
    )
    {
        try
        {
            executor.get_tensor(
                name
            );

            std::cout
                << name
                << ": NOT released"
                << std::endl;
        }
        catch(
            const std::exception&
        )
        {
            std::cout
                << name
                << ": released"
                << std::endl;
        }
    }


    // --------------------------------------------------
    // Test 3:
    // Memory Pool statistics
    // --------------------------------------------------

    std::size_t block_count =
        executor.memory_block_count();

    std::size_t pool_capacity =
        executor.memory_capacity_count();


    std::cout
        << std::endl
        << "Memory Pool Stats:"
        << std::endl;


    std::cout
        << "Block count: "
        << block_count
        << std::endl;


    std::cout
        << "Pool capacity: "
        << pool_capacity
        << " floats"
        << std::endl;


    // --------------------------------------------------
    // Compare with naive independent allocation
    // --------------------------------------------------

    std::size_t naive_capacity =
        6   // Q
        + 6 // K
        + 6 // V
        + 9 // scores
        + 9 // weights
        + 6; // output


    std::cout
        << "Naive capacity: "
        << naive_capacity
        << " floats"
        << std::endl;


    std::cout
        << "Memory saved: "
        << (
            naive_capacity
            -
            pool_capacity
        )
        << " floats"
        << std::endl;


    std::cout
        << std::boolalpha;


    std::cout
        << "Memory reuse occurred: "
        << (
            pool_capacity
            <
            naive_capacity
        )
        << std::endl;


    return 0;
}